version: '3'
services:
  redis-node-1:
    image: redis:6.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-node-1/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7001:7001"
      - "17001:17001"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.1

  redis-node-2:
    image: redis:6.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-node-2/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7002:7002"
      - "17002:17002"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.2

  redis-node-3:
    image: redis:6.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-node-3/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7003:7003"
      - "17003:17003"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.3

  redis-node-4:
    image: redis:6.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-node-4/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7004:7004"
      - "17004:17004"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.4

  redis-node-5:
    image: redis:6.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-node-5/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7005:7005"
      - "17005:17005"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.5

  redis-node-6:
    image: redis:6.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-node-6/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7006:7006"
      - "17006:17006"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.6

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
