# Spring Boot Application Configuration
spring:
  profiles:
    active: local
  application:
    name: playground
  datasource:
    url: jdbc:mysql://localhost:3306/playground_test?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
# JWT Configuration
jwt:
  access:
    secret: 9295d3232d3428c866241359d89485431868fa3c0207ab2fef5b2dff1a371ea95a9df0b74588f1d34bb6c2ce0078e39d8b9faf32c36cf97b56c09e8876007416
    expire: 86400000
  refresh:
    secret: e3545b171440dc2bddb1757e49c8b1470221d243f986a19dec44669d3c0d0f9437b4cf769756b9a2197e605e9b1924bb58faac5f578424be00ea92369fcc521d
    expire: 2592000000
# Redis Configuration
redis-cluster:
  host1: localhost
  host2: localhost
  host3: localhost
  port1: 7001
  port2: 7002
  port3: 7003
  timeout:
    socket: 5000
    client: 500
redis:
  host: localhost
  port: 6379