### 로그인
POST {{host}}/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "mingyu-gest@test.com",
  "password": "1Q2w3e4r!"
}

> {%
    client.global.set("auth_token", response.body.result.accessToken);
%}

### 로그아웃
DELETE {{host}}/api/v1/auth/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.global.set("auth_token", '');
%}

### 회원가입
POST {{host}}/api/v1/auth/signup
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "김민규",
  "password": "1Q2w3e4r!",
  "passwordCheck": "1Q2w3e4r33!",
  "email": "mingyu-gest@test.com",
  "phone": "01011223344",
  "address": "asdfasdfasdf"
}
