### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "mingyu3@test.com",
  "password": "1Q2w3e4r!"
}

### Logout
DELETE http://localhost:8080/api/v1/auth/logout
Content-Type: application/json
Accept: application/json

### Insert Member
POST http://localhost:8080/api/v1/member
Content-Type: application/json
Accept: application/json

{
  "name": "김민규",
  "password": "1Q2w3e4r!",
  "email": "mingyu@test.com",
  "phone": "01022223356",
  "address": "asdfasdfasdf"
}

### Get Members
GET http://localhost:8080/api/v1/member/list
Content-Type: application/json
Accept: application/json

### Get Member By Email
GET http://localhost:8080/api/v1/member/mingyu2@test.com
Content-Type: application/json
Accept: application/json

### Delete member By Email
DELETE http://localhost:8080/api/v1/member/mingyu2@test.com
Content-Type: application/json
Accept: application/json

### Update Member By Email
PUT http://localhost:8080/api/v1/member/mingyu2@test.com
Content-Type: application/json
Accept: application/json

{
  "name": "김민규수정",
  "password": "1q2w3E4r!##",
  "phone": "01012345678",
  "address": "asdfasasdfasdfsadfjlsadfjlsadfjlasdfjdfasdf"
}