### Login
POST {{host}}/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "mingyu3@test.com",
  "password": "1Q2w3e4r!"
}

> {%
    client.global.set("auth_token", response.body.result.accessToken);
%}


### Logout
DELETE {{host}}/api/v1/auth/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### Insert Member
POST {{host}}/api/v1/member
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "김민규",
  "password": "1Q2w3e4r!",
  "email": "mingyu33@test.com",
  "phone": "01022223326",
  "address": "asdfasdfasdf"
}

### Get Members
GET {{host}}/api/v1/member/list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Member By Email
GET {{host}}/api/v1/member/mingyu2@test.com
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### Delete member By Email
DELETE {{host}}/api/v1/member/mingyu2@test.com
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### Update Member By Email
PUT {{host}}/api/v1/member/mingyu2@test.com
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "김민규수정",
  "password": "1q2w3E4r!##",
  "phone": "01012345678",
  "address": "asdfasasdfasdfsadfjlsadfjlsadfjlasdfjdfasdf"
}