#Server Configuration
server:
  port: 18081

#Eureka Configuration
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# JWT Configuration
jwt:
  access:
    secret: {jwt.access.secret}
    expire: 86400000
  refresh:
    secret: {jwt.refresh.secret}
    expire: 2592000000

#Spring Configuration
spring:
  application:
    name: auth-api
  profiles:
    include:
      - database
      - redis
    active: local
  config:
    import: configserver:http://localhost:8888
  cloud:
    vault:
      token: playground
      uri: http://localhost:8888
    config:
      uri: http://localhost:8888
      profile: default

# Swagger Configuration
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api/v1/auth/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json