server:
  port: 18083

spring:
  application:
    name: mail-api
  profiles:
    include:
      - core
      - database
      - producer
    active: local

#Eureka Configuration
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Swagger Configuration
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api/v1/mail/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json