server:
  port: 8761 # 기본포트 8761

spring:
  application:
    name: playground # 서버 이름

eureka:
  client:
    register-with-eureka: false # eureka 서버에 등록할지 여부 - 자기 자신은 등록하지 않음
    fetch-registry: false # eureka 서버에서 정보를 가져올지 여부