server:
  port: 8888

spring:
  profiles:
    active: vault
  application:
    name: playground-config-server
  cloud:
    vault:
      token: playground
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          backend: secret
          default-key: dev
          authentication: TOKEN
          token: playground
          kv-version: 2