

# Redis Configuration
redis-cluster:
  host1: localhost
  host2: localhost
  host3: localhost
  port1: 7001
  port2: 7002
  port3: 7003
  timeout:
    socket: 5000
    client: 500
redis:
  host: localhost
  port: 6379